name: Build & Test

on:
  pull_request:

  push:
    branches:
      - master
      - devel


jobs:

  build-test:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y binutils build-essential perl libgmp-dev

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install gmp

      - name: Build
        run: |
          cd src && make world

      - name: Test compiler and runtime system
        run: |
          cd src/test
          make current cleaned
          diff cleaned-result cleaned-result.ok

      - name: Test mosmllib
        run: |
          cd src/mosmllib/test
          make current cleaned
          diff cleaned-result cleaned-result.ok
